# Generated by Django 5.2.14 on 2026-05-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogtagindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 tahtea'), (2, '2 tahtea'), (3, '3 tahtea'), (4, '4 tahtea'), (5, '5 tahtea')], default=5),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
