# Generated by Django 5.2.14 on 2026-05-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpage_rating_blogpage_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='location',
            field=models.CharField(blank=True, default='Helsinki, Finland', max_length=120),
        ),
    ]
