# Generated by Django 5.2.14 on 2026-05-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_blogpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='price',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='product',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
