# Generated by Django 5.2.14 on 2026-05-21 19:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpage_price_blogpage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='fries',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='overall',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='service',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='taste',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
