# Generated by Django 5.2.14 on 2026-05-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpage_fries_blogpage_overall_blogpage_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='body',
        ),
    ]
